package com.icooding.practice.nio;

/**
 * project_name icooding-practice
 * class ContentType
 * date  2017/11/9
 * author ibm
 * version 1.0
 */
public enum  ContentType {
    APPLICATION_XLT("xlt","application/vnd.ms-excel"),
    APPLICATION_FIF("fif","application/fractals"),
    APPLICATION_XLW("xlw","application/vnd.ms-excel"),
    TEXT_CSS("css","text/css"),
    APPLICATION_PS("ps","application/postscript"),
    VIDEO_MOVIE("movie","video/x-sgi-movie"),
    APPLICATION_SETPAY("setpay","application/set-payment-initiation"),
    APPLICATION_PMA("pma","application/x-perfmon"),
    APPLICATION_BIN("bin","application/octet-stream"),
    APPLICATION_PMC("pmc","application/x-perfmon"),
    APPLICATION_DMS("dms","application/octet-stream"),
    APPLICATION_PML("pml","application/x-perfmon"),
    APPLICATION_DER("der","application/x-x509-ca-cert"),
    APPLICATION_EXE("exe","application/octet-stream"),
    APPLICATION_PMR("pmr","application/x-perfmon"),
    APPLICATION_TEXI("texi","application/x-texinfo"),
    APPLICATION_SST("sst","application/vnd.ms-pkicertstore"),
    APPLICATION_SCD("scd","application/x-msschedule"),
    TEXT_BAS("bas","text/plain"),
    VIDEO_MOV("mov","video/quicktime"),
    APPLICATION_DVI("dvi","application/x-dvi"),
    APPLICATION_PMW("pmw","application/x-perfmon"),
    APPLICATION_AXS("axs","application/olescript"),
    APPLICATION_WKS("wks","application/vnd.ms-works"),
    AUDIO_RAM("ram","audio/x-pn-realaudio"),
    VIDEO_MPA("mpa","video/mpeg"),
    APPLICATION_WCM("wcm","application/vnd.ms-works"),
    APPLICATION_ZIP("zip","application/zip"),
    VIDEO_MPE("mpe","video/mpeg"),
    VIDEO_QT("qt","video/quicktime"),
    APPLICATION_CDF("cdf","application/x-netcdf"),
    IMAGE_RAS("ras","image/x-cmu-raster"),
    TEXT_SCT("sct","text/scriptlet"),
    VIDEO_MPG("mpg","video/mpeg"),
    APPLICATION_BCPIO("bcpio","application/x-bcpio"),
    APPLICATION_CLP("clp","application/x-msclip"),
    APPLICATION_TEX("tex","application/x-tex"),
    APPLICATION_AI("ai","application/postscript"),
    APPLICATION_EPS("eps","application/postscript"),
    APPLICATION_OCTET_STREAM("*","application/octet-stream"),
    APPLICATION_STL("stl","application/vnd.ms-pkistl"),
    APPLICATION_MPP("mpp","application/vnd.ms-project"),
    APPLICATION_ODA("oda","application/oda"),
    APPLICATION_TEXINFO("texinfo","application/x-texinfo"),
    TEXT_STM("stm","text/html"),
    IMAGE_PNM("pnm","image/x-portable-anymap"),
    AUDIO_RA("ra","audio/x-pn-realaudio"),
    APPLICATION_WDB("wdb","application/vnd.ms-works"),
    AUDIO_AU("au","audio/basic"),
    MESSAGE_MHT("mht","message/rfc822"),
    APPLICATION_DOC("doc","application/msword"),
    AUDIO_AIF("aif","audio/x-aiff"),
    APPLICATION_PFX("pfx","application/x-pkcs12"),
    IMAGE_XWD("xwd","image/x-xwindowdump"),
    APPLICATION_DOT("dot","application/msword"),
    APPLICATION_III("iii","application/x-iphone"),
    APPLICATION_JS("js","application/x-javascript"),
    AUDIO_MID("mid","audio/mid"),
    APPLICATION_M13("m13","application/x-msmediaview"),
    X_WORLD_XOF("xof","x-world/x-vrml"),
    IMAGE_CMX("cmx","image/x-cmx"),
    APPLICATION_M14("m14","application/x-msmediaview"),
    APPLICATION_WMF("wmf","application/x-msmetafile"),
    APPLICATION_CER("cer","application/x-x509-ca-cert"),
    APPLICATION_POT("pot","application/vnd.ms-powerpoint"),
    APPLICATION_SH("sh","application/x-sh"),
    IMAGE_PGM("pgm","image/x-portable-graymap"),
    TEXT_VCF("vcf","text/x-vcard"),
    IMAGE_JPEG("jpeg","image/jpeg"),
    APPLICATION_MAN("man","application/x-troff-man"),
    APPLICATION_DXR("dxr","application/x-director"),
    TEXT_C("c","text/plain"),
    APPLICATION_LHA("lha","application/octet-stream"),
    APPLICATION_RTF("rtf","application/rtf"),
    IMAGE_SVG("svg","image/svg+xml"),
    APPLICATION_TGZ("tgz","application/x-compressed"),
    AUDIO_SND("snd","audio/basic"),
    IMAGE_JFIF("jfif","image/pipeg"),
    TEXT_H("h","text/plain"),
    IMAGE_PPM("ppm","image/x-portable-pixmap"),
    VIDEO_MPV2("mpv2","video/mpeg"),
    X_WORLD_VRML("vrml","x-world/x-vrml"),
    X_WORLD_FLR("flr","x-world/x-vrml"),
    TEXT_TXT("txt","text/plain"),
    APPLICATION_PPS("pps","application/vnd.ms-powerpoint"),
    APPLICATION_SHAR("shar","application/x-shar"),
    APPLICATION_T("t","application/x-troff"),
    IMAGE_XPM("xpm","image/x-xpixmap"),
    APPLICATION_PPT("ppt","application/vnd.ms-powerpoint"),
    VIDEO_ASF("asf","video/x-ms-asf"),
    TEXT_RTX("rtx","text/richtext"),
    IMAGE_COD("cod","image/cis-cod"),
    APPLICATION_Z("z","application/x-compress"),
    APPLICATION_P7B("p7b","application/x-pkcs7-certificates"),
    APPLICATION_CPIO("cpio","application/x-cpio"),
    APPLICATION_P7C("p7c","application/x-pkcs7-mime"),
    APPLICATION_TR("tr","application/x-troff"),
    APPLICATION_MSG("msg","application/vnd.ms-outlook"),
    VIDEO_ASR("asr","video/x-ms-asf"),
    APPLICATION_SWF("swf","application/x-shockwave-flash"),
    IMAGE_BMP("bmp","image/bmp"),
    APPLICATION_ISP("isp","application/x-internet-signup"),
    APPLICATION_P7M("p7m","application/x-pkcs7-mime"),
    VIDEO_ASX("asx","video/x-ms-asf"),
    APPLICATION_ROFF("roff","application/x-troff"),
    APPLICATION_P7R("p7r","application/x-pkcs7-certreqresp"),
    APPLICATION_DIR("dir","application/x-director"),
    APPLICATION_LATEX("latex","application/x-latex"),
    APPLICATION_P7S("p7s","application/x-pkcs7-signature"),
    APPLICATION_HQX("hqx","application/mac-binhex40"),
    APPLICATION_P10("p10","application/pkcs10"),
    AUDIO_RMI("rmi","audio/mid"),
    APPLICATION_P12("p12","application/x-pkcs12"),
    IMAGE_TIF("tif","image/tiff"),
    IMAGE_ICO("ico","image/x-icon"),
    APPLICATION_ACX("acx","application/internet-property-stream"),
    APPLICATION_ME("me","application/x-troff-me"),
    TEXT_HTML("html","text/html"),
    APPLICATION_LZH("lzh","application/octet-stream"),
    X_WORLD_XAF("xaf","x-world/x-vrml"),
    APPLICATION_TAR("tar","application/x-tar"),
    APPLICATION_PRF("prf","application/pics-rules"),
    APPLICATION_MS("ms","application/x-troff-ms"),
    APPLICATION_SPC("spc","application/x-pkcs7-certificates"),
    TEXT_ETX("etx","text/x-setext"),
    MESSAGE_MHTML("mhtml","message/rfc822"),
    APPLICATION_MDB("mdb","application/x-msaccess"),
    APPLICATION_SPL("spl","application/futuresplash"),
    APPLICATION_TRM("trm","application/x-msterminal"),
    TEXT_323("323","text/h323"),
    APPLICATION_NC("nc","application/x-netcdf"),
    VIDEO_MPEG("mpeg","video/mpeg"),
    IMAGE_PBM("pbm","image/x-portable-bitmap"),
    APPLICATION_WPS("wps","application/vnd.ms-works"),
    TEXT_ULS("uls","text/iuls"),
    VIDEO_LSF("lsf","video/x-la-asf"),
    IMAGE_XBM("xbm","image/x-xbitmap"),
    IMAGE_TIFF("tiff","image/tiff"),
    AUDIO_AIFF("aiff","audio/x-aiff"),
    IMAGE_GIF("gif","image/gif"),
    AUDIO_AIFC("aifc","audio/x-aiff"),
    IMAGE_IEF("ief","image/ief"),
    MESSAGE_NWS("nws","message/rfc822"),
    IMAGE_RGB("rgb","image/x-rgb"),
    AUDIO_M3U("m3u","audio/x-mpegurl"),
    VIDEO_LSX("lsx","video/x-la-asf"),
    APPLICATION_DCR("dcr","application/x-director"),
    APPLICATION_HTA("hta","application/hta"),
    APPLICATION_CRD("crd","application/x-mscardfile"),
    APPLICATION_PKO("pko","application/ynd.ms-pkipko"),
    VIDEO_AVI("avi","video/x-msvideo"),
    APPLICATION_SV4CRC("sv4crc","application/x-sv4crc"),
    TEXT_TSV("tsv","text/tab-separated-values"),
    TEXT_HTC("htc","text/x-component"),
    APPLICATION_CAT("cat","application/vnd.ms-pkiseccat"),
    APPLICATION_SV4CPIO("sv4cpio","application/x-sv4cpio"),
    APPLICATION_MVB("mvb","application/x-msmediaview"),
    APPLICATION_CRL("crl","application/pkix-crl"),
    APPLICATION_TCL("tcl","application/x-tcl"),
    APPLICATION_CLASS("class","application/octet-stream"),
    IMAGE_JPE("jpe","image/jpeg"),
    APPLICATION_SIT("sit","application/x-stuffit"),
    IMAGE_JPG("jpg","image/jpeg"),
    TEXT_HTM("htm","text/html"),
    APPLICATION_USTAR("ustar","application/x-ustar"),
    APPLICATION_CRT("crt","application/x-x509-ca-cert"),
    APPLICATION_DLL("dll","application/x-msdownload"),
    APPLICATION_SRC("src","application/x-wais-source"),
    APPLICATION_EVY("evy","application/envoy"),
    TEXT_HTT("htt","text/webviewhtml"),
    APPLICATION_HDF("hdf","application/x-hdf"),
    APPLICATION_XLA("xla","application/vnd.ms-excel"),
    APPLICATION_HLP("hlp","application/winhlp"),
    AUDIO_WAV("wav","audio/x-wav"),
    APPLICATION_XLC("xlc","application/vnd.ms-excel"),
    APPLICATION_GTAR("gtar","application/x-gtar"),
    VIDEO_MP2("mp2","video/mpeg"),
    APPLICATION_INS("ins","application/x-internet-signup"),
    APPLICATION_WRI("wri","application/x-mswrite"),
    X_WORLD_WRL("wrl","x-world/x-vrml"),
    APPLICATION_SETREG("setreg","application/set-registration-initiation"),
    AUDIO_MP3("mp3","audio/mpeg"),
    APPLICATION_PDF("pdf","application/pdf"),
    APPLICATION_GZ("gz","application/x-gzip"),
    APPLICATION_XLM("xlm","application/vnd.ms-excel"),
    APPLICATION_CSH("csh","application/x-csh"),
    APPLICATION_MNY("mny","application/x-msmoney"),
    APPLICATION_PUB("pub","application/x-mspublisher"),
    APPLICATION_XLS("xls","application/vnd.ms-excel"),
    X_WORLD_WRZ("wrz","x-world/x-vrml");

    public String key;

    public String value;

    ContentType(String key, String value) {
        this.key = key;
        this.value = value;
    }

    public static ContentType parse(String name){
        int index = name.lastIndexOf(".");
        String key = name.substring(index!=-1?index+1:0);
        for (ContentType contentType : ContentType.values()) {
            if(contentType.key.equals(key)){
                return contentType;
            }
        }
        return ContentType.TEXT_HTML;
    }

}
